tabela = ('Botafogo','Fortaleza', 'Palmeiras', 'Flamengo', 'Cruzeiro', 'São Paulo', 'Bahia', 'Internacional', 'Vasco da gama', 'Atlético-MG', 'Bragantino', 'Athletico-PR', 'Juventude', 'Criciuma', 'Gremio', 'Fluminense','Corinthians', 'EC Vitória', 'Cuiabá', 'Atlético-GO')
print(50*'=')
print('               TABELA DO BRASILEIRÂO')
print(50*'=')
print('O time', tabela[7], 'esta em 8°')
print(50*'-')
print('Os 5 primeitos times da tabela são: ',tabela[0:5])
print(50*'-')
tabelaordenada = sorted(tabela) 
print('Os time em ordem alfabetica são',tabelaordenada)
print(50*'-')
print('No Z4 estão: ',tabela[16:21])
print(50*'-')
print('Atualizada no dia 12/09/2024')